security:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: 86400000
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST_AWS}:${DB_PORT_AWS}/${DB_NAME_AWS}
    username: ${DB_USER_AWS}
    password: ${DB_PASS_AWS}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  mvc:
    dispatch-options-request: true
logging:
  level:
    root: warn
management:
  endpoints:
    web:
      exposure:
        include: 'health'