security:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
  jwt:
    secret-key: ${JWT_SECRET_KEY_DEV}
    expiration-time: 86400000
spring:
  datasource:
    url: ${DB_URL_DEV}
    username: ${DB_USER_DEV}
    password: ${DB_PASS_DEV}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    root: info
management:
  endpoints:
    web:
      exposure:
        include: 'health'
