security:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
  jwt:
    secret-key: ${JWT_SECRET_KEY_TEST}
    expiration-time: 86400000
spring:
  datasource:
    url: jdbc:h2:mem:testDb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    root: warn
server:
  error:
    include-exception: true